---
name: garden-runc

releases:
- name: garden-runc
  version: 1.9.6
  sha1: 55fdcc0f2bda526f126d28827fbae7b21c6b0d1c
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.9.6

resource_pools:
- name: vms
  network: default
  env:
    bosh:
      password: '*'

disk_pools:
- name: disks
  disk_size: 32_768

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    static_ips: ((internal_ip))
    dns: [8.8.8.8]

instance_groups:
- name: garden
  instances: 1
  resource_pool: vms
  persistent_disk_pool: disks
  networks:
  - name: default
    default: [gateway,dns]
  jobs:
  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        debug_listen_address: 0.0.0.0:17013

cloud_provider:
  mbus: https://mbus:((mbus_bootstrap_password))@((public_ip)):6868
  properties:
    agent: 
      mbus: https://mbus:((mbus_bootstrap_password))@0.0.0.0:6868
    blobstore: 
      provider: local
      path: /var/vcap/micro_bosh/data/cache
    ntp:
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com

variables:
- name: mbus_bootstrap_password
  type: password
